### ISSUE TITLE
Doesn't run as expected in Readme

### ISSUE THREAD

**Issue by DanielTate** [martonlederer/esbuild-plugin-postcss2#10]
`npm install -D esbuild esbuild-plugin-postcss2`

create build.js

```
    const esbuild = require('esbuild')
    const postCssPlugin = require('esbuild-plugin-postcss2')

    // Build CSS
    esbuild.build({
        entryPoints: ['src/css/app.css'],
        plugins: [
            postCssPlugin()
        ],
        outfile: 'dist/css/app.css'
    })
```

run `node build.js`

_**Error: postCssPlugin() is not a function**_

**Comment by DanielTate** [comment]
I also tested with Yarn yielding the same result. I noticed in your package you are exporting `postCSSPlugin` not `postCssPlugin` I did try both but didn't seem to get anywhere. Any insight would be great.

**Comment by martonlederer** [comment]
If you use ES modules, the default import should work. If not, just use it like this: https://github.com/th8ta/ArConnect/blob/3aa0ee9108ec430dd07303076517fb6df8dc3770/esbuild.js#L36

**Comment by DanielTate** [comment]
Thanks you can close this issue. If I could suggest you add that as a small note for people writing build scripts, it might be helpful to give that option right away.

```
esbuild.build({
    ...
    plugins: [
        postCssPlugin.default({
            plugins: [ ... ]
        })
    ],
    ...
})
```
