### ISSUE TITLE
Usage with sass

### ISSUE THREAD

**Issue by 8lall0** [martonlederer/esbuild-plugin-postcss2#11]
Hi,

i sincerely didn't understand how to use this with sass. Can you explain that to me?

Thanks!

**Comment by martonlederer** [comment]
Hey there, it's actually very easy. You only need to install the preprocessor:
```sh
npm i sass
```
or
```sh
npm i node-sass
```

Hope this helps :)

**Comment by 8lall0** [comment]
That's awesome, thank you!

**Comment by martonlederer** [comment]
Happy to help :)
