### ISSUE TITLE
`url` files not found

### ISSUE THREAD

**Issue by Intrepidd** [martonlederer/esbuild-plugin-postcss2#20]
I'm trying to compile my style which has references to font files via `src: url("../path/some-font.ttf")`

I'm getting the following error : 

```
 > ../../../../var/folders/5l/br5w2k5d4f32hmcysvmf0gjh0000gn/T/tmp-22896-OBMEyq54PUj8/17babdb14690/application.css:2281:11: error: Could not resolve "../path/some-font.ttf"
    2281 │   src: url('../path/some-font.ttf');
         ╵            ~~~~~~~~~~~~~~~~~~~~
    at failureErrorWithLog (homepath/node_modules/esbuild/lib/main.js:1451:15)
    at homepath/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (homepath/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (homepath/node_modules/esbuild/lib/main.js:1129:7)
    at homepath/node_modules/esbuild/lib/main.js:1238:14
    at homepath/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (homepath/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (homepath/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
```

Am I missing something ?

Thanks !

**Comment by Intrepidd** [comment]
I managed to fix this by adding `require('postcss-url')({ url: 'inline' })` to my plugins, hope it can help.

cc @thanosbellos and @dubstepKnight who 👍 this post

**Comment by martpie** [comment]
I'm sorry @Intrepidd, where did you use this code exactly? Are you handling PostCSS with custom plugins that you're able to manage yourself?

**Comment by Intrepidd** [comment]
@martpie Yes !

I don't use the esbuild cli, I rather use a `build.js` file. [It is documented here](https://esbuild.github.io/getting-started/#build-scripts)

Mine looks like this : 

```
const esbuild = require('esbuild')
const postCssPlugin = require('esbuild-plugin-postcss2')
const { stimulusPlugin } = require('esbuild-plugin-stimulus')

esbuild.build({
  entryPoints: [
    'app/packs/entrypoints/application.js',
    'app/packs/entrypoints/foundation_emails.js',
    'app/packs/entrypoints/uppy.css',
    'app/packs/entrypoints/tinymce.css'
  ],
  bundle: true,
  splitting: true,
  format: 'esm',
  outdir: 'app/assets/builds',
  target: 'es2016',
  watch: process.argv.includes('--watch'),
  plugins: [
    stimulusPlugin(),
    postCssPlugin.default({
      plugins: [
        require('postcss-import'),
        require('postcss-url')({ url: 'inline' }),
        require('tailwindcss')({ config: './app/packs/css/tailwind.cjs' }),
        require('autoprefixer'),
        require('postcss-flexbugs-fixes')
      ]
    })
  ]
}).then(result => {
  console.log(result)
})
```

**Comment by thomasgrade** [comment]
@Intrepidd I use require('postcss-url')({ url: 'inline' }) in my config to resolve less file, but i got nothing.
here is my config:
![image](https://user-images.githubusercontent.com/34702077/168975975-05acce2f-557e-4122-9d15-2a2e3e2a7060.png)
after build i get nothing but js file. could you tell how to fix it ?

**Comment by Intrepidd** [comment]
@thomasgrade i don't think this is related to this plug-in.

Are you importing your less files properly from your js / ts?

On a side note, I decided to run postcss standalone to generate my css rather than running it within esbuild, as I encountered other problems down the road

**Comment by thomasgrade** [comment]
@Intrepidd when i use config like this
![image](https://user-images.githubusercontent.com/34702077/168982178-071197e8-e9bd-4103-b191-0f053268b2e9.png)
i can get js and css file, like this:
![image](https://user-images.githubusercontent.com/34702077/168982604-78ab4ba7-5ac4-4b56-9806-19b9142f093d.png)
but this config cannot resovle url() in less. it will throw error as above.
when i use  require('postcss-url')({ url: 'inline' }),it do not throw error. but css file disappear in lib folder
